name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0

    - name: Set up MSBuild path
      uses: microsoft/setup-msbuild@v2

    - name: Build solution
      run: msbuild Graphics-Playgrounds.sln /p:Configuration=Release /p:Platform="x64"
